<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game.proto

namespace GPBMetadata;

class Game
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A:\x0A\x0Agame.proto\"\x14\x0A\x04Game\x12\x0C\x0A\x04name\x18\x01 \x01(\x09B\x0E\xE2\x02\x0BGPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

